[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tracelet"
version = "0.1.0"
description = "Lightweight APM for Python"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "sqlalchemy>=2.0.0",
]

[tool.setuptools]
packages = ["tracelet"]